// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCardBack(arg1:string):Promise<string>;

export function GetCardFront(arg1:string):Promise<string>;
