// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCardBack(arg1) {
  return window['go']['main']['Cards']['GetCardBack'](arg1);
}

export function GetCardFront(arg1) {
  return window['go']['main']['Cards']['GetCardFront'](arg1);
}

export function GetTotalCards() {
  return window['go']['main']['Cards']['GetTotalCards']();
}

export function UpdateCard(arg1, arg2) {
  return window['go']['main']['Cards']['UpdateCard'](arg1, arg2);
}
